# This file stores configurations for your Shopify app.

name = "Printful Custom"
client_id = "f73fd9d2dc065bf8e5392c093bb610e9"
application_url = "https://printful-custom-production.up.railway.app"
embedded = true

[auth]
redirect_urls = [ "https://printful-custom-production.up.railway.app/auth/callback" ]

[access_scopes]
scopes = "write_orders,read_orders,read_products,write_files,read_files"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks/orders/create"

[app_proxy]
url = "https://printful-custom-production.up.railway.app/api"
subpath = "proxy"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
